# This template contains enough information for documenteer to build

[project]
# The title of the index page.
title = "ts_mtaos" # i.e. CBP
# Copyright information displayed on the footer of each page
copyright = "2019-2026 Association of Universities for Research in Astronomy, Inc. (AURA)"
github_url = "https://github.com/lsst-ts/ts_mtaos"

[project.python]
# pyproject.toml package name, fills out unseen metadata
package = "ts_mtaos" # i.e. ts_cbp (should match the name that importlib.metadata uses/pyproject.toml name)
documentation_url_key = "documentation"
github_url_key = "source_code"

[sphinx]
extensions = [
  "sphinx-jsonschema",
  "sphinxcontrib.plantuml",
]

[sphinx.intersphinx.projects]
ts-xml = "https://ts-xml.lsst.io"
ts-wep = "https://ts-wep.lsst.io"
ts-ofc= "https://ts-ofc.lsst.io"
salobj = "https://ts-salobj.lsst.io"
python = "https://docs.python.org/3.13/"
