name: lint

on:
  - push
  - pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install
        run: |
          $CONDA/bin/conda install -c lsstts python=3.11 ts-pre-commit-config -y

      - name: Generate pre commit configuration
        run: |
          PATH=${PATH}:$CONDA/bin generate_pre_commit_conf

      - name: Run pre commit checks
        run: $CONDA/bin/pre-commit run --all
